// The markup in webready.html: <picture> for images, <video> for videos.

import { VERSION } from "./manifest.js";

/** A rendition's URL: under `publicPath` when set, else relative to the output folder. */
export function urlFor(file, publicPath) {
  return publicPath ? `${publicPath}/${file}` : file;
}

const escapeAttr = (value) => String(value).replace(/&/g, "&amp;").replace(/"/g, "&quot;");

/** Renditions grouped by format, each list narrowest first. */
export function byFormat(entry) {
  const groups = Object.fromEntries(entry.formats.map((format) => [format, []]));
  for (const r of entry.renditions) groups[r.format]?.push(r);
  for (const list of Object.values(groups)) list.sort((a, b) => a.width - b.width);
  return groups;
}

/**
 * <picture> markup for an image entry.
 *
 * - "srcset": one <source> per format with srcset + sizes - the browser picks
 *   by slot width and screen density.
 * - "media": one <source> per width and format, chosen by viewport width.
 *
 * The <img> fallback is the largest rendition in the last (most widely
 * supported) format, with width and height so the browser reserves space.
 */
export function pictureMarkup(entry, { style = "srcset", publicPath = null, sizes = "100vw" } = {}) {
  const groups = byFormat(entry);
  const url = (r) => escapeAttr(urlFor(r.file, publicPath));
  const fallback = groups[entry.formats.at(-1)];
  const largest = fallback.at(-1);
  const lines = ["<picture>"];

  if (style === "media") {
    // The browser takes the first <source> whose media AND type match, so
    // for each width, every format in order of preference.
    const widths = fallback.map((r) => r.width);
    widths.forEach((width, i) => {
      const last = i === widths.length - 1;
      for (const format of entry.formats) {
        const r = groups[format].find((x) => x.width === width);
        if (!r) continue;
        const media = last ? "" : ` media="(max-width: ${width}px)"`;
        lines.push(`  <source type="image/${format}"${media} srcset="${url(r)}">`);
      }
    });
  } else {
    for (const format of entry.formats) {
      const srcset = groups[format].map((r) => `${url(r)} ${r.width}w`).join(", ");
      lines.push(`  <source type="image/${format}" sizes="${escapeAttr(sizes)}"`);
      lines.push(`          srcset="${srcset}">`);
    }
  }

  lines.push(
    `  <img src="${url(largest)}" alt="" width="${largest.width}" height="${largest.height}" loading="lazy" decoding="async">`,
    "</picture>",
  );
  return lines.join("\n");
}

/**
 * The <video> sources, widest first, each but the last limited by a
 * min-width media query. Videos have no srcset; the choice is made once,
 * when the element loads.
 */
export function videoSources(entry) {
  const sorted = [...entry.renditions].sort((a, b) => b.width - a.width);
  return sorted.map((r, i) => ({
    rendition: r,
    media: i < sorted.length - 1 ? `(min-width: ${sorted[i + 1].width + 1}px)` : null,
  }));
}

export function videoMarkup(entry, { publicPath = null } = {}) {
  const url = (file) => escapeAttr(urlFor(file, publicPath));
  const poster = entry.poster ? ` poster="${url(entry.poster)}"` : "";
  const lines = [
    `<video controls playsinline preload="metadata" width="${entry.width}" height="${entry.height}"${poster}>`,
  ];
  for (const { rendition, media } of videoSources(entry)) {
    lines.push(`  <source src="${url(rendition.file)}"${media ? ` media="${media}"` : ""} type="video/mp4">`);
  }
  lines.push("</video>");
  return lines.join("\n");
}

/**
 * webready.html: the markup for every file, ready to paste. Opened in a
 * browser it also previews everything when the paths are relative.
 */
export function renderMarkup(manifest, { style = "srcset", publicPath = manifest.publicPath ?? null } = {}) {
  const blocks = [
    "<!--",
    `  Generated by webready ${VERSION} — https://github.com/sajjadlabs/webready`,
    "",
    "  Copy the markup you need.",
    publicPath
      ? `  URLs start with ${publicPath}.`
      : "  Paths are relative to this folder; set publicPath to get site URLs.",
    style === "media"
      ? "  Images switch by viewport width (media). For browser-chosen, density-aware images use markup \"srcset\"."
      : "  Images use srcset + sizes: set sizes to how wide each image is displayed (100vw = full width).",
    "  Videos choose a source once, when they load; resizing doesn't switch it.",
    "-->",
  ];
  for (const [source, entry] of Object.entries(manifest.images)) {
    blocks.push("", `<!-- ${source} -->`, pictureMarkup(entry, { style, publicPath }));
  }
  for (const [source, entry] of Object.entries(manifest.videos)) {
    blocks.push("", `<!-- ${source} -->`, videoMarkup(entry, { publicPath }));
  }
  return `${blocks.join("\n")}\n`;
}
