name: Feature request
description: An idea to make webready more useful
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What are you trying to do?
      description: The problem or use case, rather than the solution.
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: What would help?
